sim_homepage:
    pattern:  /
    defaults: { _controller: SimBundle:Users:index }

login:
    pattern: /login
    defaults: { _controller: SimBundle:Users:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout
